// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Chat.proto

package cn.krossframework.proto;

public final class Chat {
  private Chat() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ChatMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cn.krossframework.proto.ChatMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 cmdType = 1;</code>
     */
    int getCmdType();

    /**
     * <code>optional string msg = 2;</code>
     */
    java.lang.String getMsg();
    /**
     * <code>optional string msg = 2;</code>
     */
    com.google.protobuf.ByteString
        getMsgBytes();

    /**
     * <code>optional int32 emoticon = 3;</code>
     */
    int getEmoticon();

    /**
     * <code>optional bytes stream = 4;</code>
     */
    com.google.protobuf.ByteString getStream();
  }
  /**
   * Protobuf type {@code cn.krossframework.proto.ChatMessage}
   */
  public  static final class ChatMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cn.krossframework.proto.ChatMessage)
      ChatMessageOrBuilder {
    // Use ChatMessage.newBuilder() to construct.
    private ChatMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ChatMessage() {
      cmdType_ = 0;
      msg_ = "";
      emoticon_ = 0;
      stream_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ChatMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              cmdType_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              msg_ = s;
              break;
            }
            case 24: {

              emoticon_ = input.readInt32();
              break;
            }
            case 34: {

              stream_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.krossframework.proto.Chat.internal_static_cn_krossframework_proto_ChatMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.krossframework.proto.Chat.internal_static_cn_krossframework_proto_ChatMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.krossframework.proto.Chat.ChatMessage.class, cn.krossframework.proto.Chat.ChatMessage.Builder.class);
    }

    public static final int CMDTYPE_FIELD_NUMBER = 1;
    private int cmdType_;
    /**
     * <code>optional int32 cmdType = 1;</code>
     */
    public int getCmdType() {
      return cmdType_;
    }

    public static final int MSG_FIELD_NUMBER = 2;
    private volatile java.lang.Object msg_;
    /**
     * <code>optional string msg = 2;</code>
     */
    public java.lang.String getMsg() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msg_ = s;
        return s;
      }
    }
    /**
     * <code>optional string msg = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMsgBytes() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EMOTICON_FIELD_NUMBER = 3;
    private int emoticon_;
    /**
     * <code>optional int32 emoticon = 3;</code>
     */
    public int getEmoticon() {
      return emoticon_;
    }

    public static final int STREAM_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString stream_;
    /**
     * <code>optional bytes stream = 4;</code>
     */
    public com.google.protobuf.ByteString getStream() {
      return stream_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (cmdType_ != 0) {
        output.writeInt32(1, cmdType_);
      }
      if (!getMsgBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, msg_);
      }
      if (emoticon_ != 0) {
        output.writeInt32(3, emoticon_);
      }
      if (!stream_.isEmpty()) {
        output.writeBytes(4, stream_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (cmdType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, cmdType_);
      }
      if (!getMsgBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, msg_);
      }
      if (emoticon_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, emoticon_);
      }
      if (!stream_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, stream_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.krossframework.proto.Chat.ChatMessage)) {
        return super.equals(obj);
      }
      cn.krossframework.proto.Chat.ChatMessage other = (cn.krossframework.proto.Chat.ChatMessage) obj;

      boolean result = true;
      result = result && (getCmdType()
          == other.getCmdType());
      result = result && getMsg()
          .equals(other.getMsg());
      result = result && (getEmoticon()
          == other.getEmoticon());
      result = result && getStream()
          .equals(other.getStream());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + CMDTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getCmdType();
      hash = (37 * hash) + MSG_FIELD_NUMBER;
      hash = (53 * hash) + getMsg().hashCode();
      hash = (37 * hash) + EMOTICON_FIELD_NUMBER;
      hash = (53 * hash) + getEmoticon();
      hash = (37 * hash) + STREAM_FIELD_NUMBER;
      hash = (53 * hash) + getStream().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.krossframework.proto.Chat.ChatMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.krossframework.proto.Chat.ChatMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.krossframework.proto.Chat.ChatMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.krossframework.proto.Chat.ChatMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.krossframework.proto.Chat.ChatMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.krossframework.proto.Chat.ChatMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.krossframework.proto.Chat.ChatMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.krossframework.proto.Chat.ChatMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.krossframework.proto.Chat.ChatMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.krossframework.proto.Chat.ChatMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.krossframework.proto.Chat.ChatMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cn.krossframework.proto.ChatMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cn.krossframework.proto.ChatMessage)
        cn.krossframework.proto.Chat.ChatMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.krossframework.proto.Chat.internal_static_cn_krossframework_proto_ChatMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.krossframework.proto.Chat.internal_static_cn_krossframework_proto_ChatMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.krossframework.proto.Chat.ChatMessage.class, cn.krossframework.proto.Chat.ChatMessage.Builder.class);
      }

      // Construct using cn.krossframework.proto.Chat.ChatMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        cmdType_ = 0;

        msg_ = "";

        emoticon_ = 0;

        stream_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.krossframework.proto.Chat.internal_static_cn_krossframework_proto_ChatMessage_descriptor;
      }

      public cn.krossframework.proto.Chat.ChatMessage getDefaultInstanceForType() {
        return cn.krossframework.proto.Chat.ChatMessage.getDefaultInstance();
      }

      public cn.krossframework.proto.Chat.ChatMessage build() {
        cn.krossframework.proto.Chat.ChatMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cn.krossframework.proto.Chat.ChatMessage buildPartial() {
        cn.krossframework.proto.Chat.ChatMessage result = new cn.krossframework.proto.Chat.ChatMessage(this);
        result.cmdType_ = cmdType_;
        result.msg_ = msg_;
        result.emoticon_ = emoticon_;
        result.stream_ = stream_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.krossframework.proto.Chat.ChatMessage) {
          return mergeFrom((cn.krossframework.proto.Chat.ChatMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.krossframework.proto.Chat.ChatMessage other) {
        if (other == cn.krossframework.proto.Chat.ChatMessage.getDefaultInstance()) return this;
        if (other.getCmdType() != 0) {
          setCmdType(other.getCmdType());
        }
        if (!other.getMsg().isEmpty()) {
          msg_ = other.msg_;
          onChanged();
        }
        if (other.getEmoticon() != 0) {
          setEmoticon(other.getEmoticon());
        }
        if (other.getStream() != com.google.protobuf.ByteString.EMPTY) {
          setStream(other.getStream());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.krossframework.proto.Chat.ChatMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.krossframework.proto.Chat.ChatMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int cmdType_ ;
      /**
       * <code>optional int32 cmdType = 1;</code>
       */
      public int getCmdType() {
        return cmdType_;
      }
      /**
       * <code>optional int32 cmdType = 1;</code>
       */
      public Builder setCmdType(int value) {
        
        cmdType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 cmdType = 1;</code>
       */
      public Builder clearCmdType() {
        
        cmdType_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object msg_ = "";
      /**
       * <code>optional string msg = 2;</code>
       */
      public java.lang.String getMsg() {
        java.lang.Object ref = msg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          msg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string msg = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMsgBytes() {
        java.lang.Object ref = msg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string msg = 2;</code>
       */
      public Builder setMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        msg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string msg = 2;</code>
       */
      public Builder clearMsg() {
        
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }
      /**
       * <code>optional string msg = 2;</code>
       */
      public Builder setMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        msg_ = value;
        onChanged();
        return this;
      }

      private int emoticon_ ;
      /**
       * <code>optional int32 emoticon = 3;</code>
       */
      public int getEmoticon() {
        return emoticon_;
      }
      /**
       * <code>optional int32 emoticon = 3;</code>
       */
      public Builder setEmoticon(int value) {
        
        emoticon_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 emoticon = 3;</code>
       */
      public Builder clearEmoticon() {
        
        emoticon_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString stream_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes stream = 4;</code>
       */
      public com.google.protobuf.ByteString getStream() {
        return stream_;
      }
      /**
       * <code>optional bytes stream = 4;</code>
       */
      public Builder setStream(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        stream_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes stream = 4;</code>
       */
      public Builder clearStream() {
        
        stream_ = getDefaultInstance().getStream();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:cn.krossframework.proto.ChatMessage)
    }

    // @@protoc_insertion_point(class_scope:cn.krossframework.proto.ChatMessage)
    private static final cn.krossframework.proto.Chat.ChatMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.krossframework.proto.Chat.ChatMessage();
    }

    public static cn.krossframework.proto.Chat.ChatMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ChatMessage>
        PARSER = new com.google.protobuf.AbstractParser<ChatMessage>() {
      public ChatMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ChatMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ChatMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ChatMessage> getParserForType() {
      return PARSER;
    }

    public cn.krossframework.proto.Chat.ChatMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ChatMessageResultOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cn.krossframework.proto.ChatMessageResult)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string from = 1;</code>
     */
    java.lang.String getFrom();
    /**
     * <code>optional string from = 1;</code>
     */
    com.google.protobuf.ByteString
        getFromBytes();

    /**
     * <code>optional bool toAll = 2;</code>
     */
    boolean getToAll();

    /**
     * <code>repeated string to = 3;</code>
     */
    java.util.List<java.lang.String>
        getToList();
    /**
     * <code>repeated string to = 3;</code>
     */
    int getToCount();
    /**
     * <code>repeated string to = 3;</code>
     */
    java.lang.String getTo(int index);
    /**
     * <code>repeated string to = 3;</code>
     */
    com.google.protobuf.ByteString
        getToBytes(int index);

    /**
     * <code>optional .cn.krossframework.proto.ChatMessage chatMessage = 4;</code>
     */
    boolean hasChatMessage();
    /**
     * <code>optional .cn.krossframework.proto.ChatMessage chatMessage = 4;</code>
     */
    cn.krossframework.proto.Chat.ChatMessage getChatMessage();
    /**
     * <code>optional .cn.krossframework.proto.ChatMessage chatMessage = 4;</code>
     */
    cn.krossframework.proto.Chat.ChatMessageOrBuilder getChatMessageOrBuilder();
  }
  /**
   * Protobuf type {@code cn.krossframework.proto.ChatMessageResult}
   */
  public  static final class ChatMessageResult extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cn.krossframework.proto.ChatMessageResult)
      ChatMessageResultOrBuilder {
    // Use ChatMessageResult.newBuilder() to construct.
    private ChatMessageResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ChatMessageResult() {
      from_ = "";
      toAll_ = false;
      to_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ChatMessageResult(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              from_ = s;
              break;
            }
            case 16: {

              toAll_ = input.readBool();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                to_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              to_.add(s);
              break;
            }
            case 34: {
              cn.krossframework.proto.Chat.ChatMessage.Builder subBuilder = null;
              if (chatMessage_ != null) {
                subBuilder = chatMessage_.toBuilder();
              }
              chatMessage_ = input.readMessage(cn.krossframework.proto.Chat.ChatMessage.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(chatMessage_);
                chatMessage_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          to_ = to_.getUnmodifiableView();
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.krossframework.proto.Chat.internal_static_cn_krossframework_proto_ChatMessageResult_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.krossframework.proto.Chat.internal_static_cn_krossframework_proto_ChatMessageResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.krossframework.proto.Chat.ChatMessageResult.class, cn.krossframework.proto.Chat.ChatMessageResult.Builder.class);
    }

    private int bitField0_;
    public static final int FROM_FIELD_NUMBER = 1;
    private volatile java.lang.Object from_;
    /**
     * <code>optional string from = 1;</code>
     */
    public java.lang.String getFrom() {
      java.lang.Object ref = from_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        from_ = s;
        return s;
      }
    }
    /**
     * <code>optional string from = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFromBytes() {
      java.lang.Object ref = from_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        from_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOALL_FIELD_NUMBER = 2;
    private boolean toAll_;
    /**
     * <code>optional bool toAll = 2;</code>
     */
    public boolean getToAll() {
      return toAll_;
    }

    public static final int TO_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList to_;
    /**
     * <code>repeated string to = 3;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getToList() {
      return to_;
    }
    /**
     * <code>repeated string to = 3;</code>
     */
    public int getToCount() {
      return to_.size();
    }
    /**
     * <code>repeated string to = 3;</code>
     */
    public java.lang.String getTo(int index) {
      return to_.get(index);
    }
    /**
     * <code>repeated string to = 3;</code>
     */
    public com.google.protobuf.ByteString
        getToBytes(int index) {
      return to_.getByteString(index);
    }

    public static final int CHATMESSAGE_FIELD_NUMBER = 4;
    private cn.krossframework.proto.Chat.ChatMessage chatMessage_;
    /**
     * <code>optional .cn.krossframework.proto.ChatMessage chatMessage = 4;</code>
     */
    public boolean hasChatMessage() {
      return chatMessage_ != null;
    }
    /**
     * <code>optional .cn.krossframework.proto.ChatMessage chatMessage = 4;</code>
     */
    public cn.krossframework.proto.Chat.ChatMessage getChatMessage() {
      return chatMessage_ == null ? cn.krossframework.proto.Chat.ChatMessage.getDefaultInstance() : chatMessage_;
    }
    /**
     * <code>optional .cn.krossframework.proto.ChatMessage chatMessage = 4;</code>
     */
    public cn.krossframework.proto.Chat.ChatMessageOrBuilder getChatMessageOrBuilder() {
      return getChatMessage();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getFromBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, from_);
      }
      if (toAll_ != false) {
        output.writeBool(2, toAll_);
      }
      for (int i = 0; i < to_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, to_.getRaw(i));
      }
      if (chatMessage_ != null) {
        output.writeMessage(4, getChatMessage());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getFromBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, from_);
      }
      if (toAll_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, toAll_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < to_.size(); i++) {
          dataSize += computeStringSizeNoTag(to_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getToList().size();
      }
      if (chatMessage_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getChatMessage());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.krossframework.proto.Chat.ChatMessageResult)) {
        return super.equals(obj);
      }
      cn.krossframework.proto.Chat.ChatMessageResult other = (cn.krossframework.proto.Chat.ChatMessageResult) obj;

      boolean result = true;
      result = result && getFrom()
          .equals(other.getFrom());
      result = result && (getToAll()
          == other.getToAll());
      result = result && getToList()
          .equals(other.getToList());
      result = result && (hasChatMessage() == other.hasChatMessage());
      if (hasChatMessage()) {
        result = result && getChatMessage()
            .equals(other.getChatMessage());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + FROM_FIELD_NUMBER;
      hash = (53 * hash) + getFrom().hashCode();
      hash = (37 * hash) + TOALL_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getToAll());
      if (getToCount() > 0) {
        hash = (37 * hash) + TO_FIELD_NUMBER;
        hash = (53 * hash) + getToList().hashCode();
      }
      if (hasChatMessage()) {
        hash = (37 * hash) + CHATMESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getChatMessage().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.krossframework.proto.Chat.ChatMessageResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.krossframework.proto.Chat.ChatMessageResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.krossframework.proto.Chat.ChatMessageResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.krossframework.proto.Chat.ChatMessageResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.krossframework.proto.Chat.ChatMessageResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.krossframework.proto.Chat.ChatMessageResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.krossframework.proto.Chat.ChatMessageResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.krossframework.proto.Chat.ChatMessageResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.krossframework.proto.Chat.ChatMessageResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.krossframework.proto.Chat.ChatMessageResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.krossframework.proto.Chat.ChatMessageResult prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cn.krossframework.proto.ChatMessageResult}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cn.krossframework.proto.ChatMessageResult)
        cn.krossframework.proto.Chat.ChatMessageResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.krossframework.proto.Chat.internal_static_cn_krossframework_proto_ChatMessageResult_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.krossframework.proto.Chat.internal_static_cn_krossframework_proto_ChatMessageResult_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.krossframework.proto.Chat.ChatMessageResult.class, cn.krossframework.proto.Chat.ChatMessageResult.Builder.class);
      }

      // Construct using cn.krossframework.proto.Chat.ChatMessageResult.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        from_ = "";

        toAll_ = false;

        to_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        if (chatMessageBuilder_ == null) {
          chatMessage_ = null;
        } else {
          chatMessage_ = null;
          chatMessageBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.krossframework.proto.Chat.internal_static_cn_krossframework_proto_ChatMessageResult_descriptor;
      }

      public cn.krossframework.proto.Chat.ChatMessageResult getDefaultInstanceForType() {
        return cn.krossframework.proto.Chat.ChatMessageResult.getDefaultInstance();
      }

      public cn.krossframework.proto.Chat.ChatMessageResult build() {
        cn.krossframework.proto.Chat.ChatMessageResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cn.krossframework.proto.Chat.ChatMessageResult buildPartial() {
        cn.krossframework.proto.Chat.ChatMessageResult result = new cn.krossframework.proto.Chat.ChatMessageResult(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.from_ = from_;
        result.toAll_ = toAll_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          to_ = to_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.to_ = to_;
        if (chatMessageBuilder_ == null) {
          result.chatMessage_ = chatMessage_;
        } else {
          result.chatMessage_ = chatMessageBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.krossframework.proto.Chat.ChatMessageResult) {
          return mergeFrom((cn.krossframework.proto.Chat.ChatMessageResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.krossframework.proto.Chat.ChatMessageResult other) {
        if (other == cn.krossframework.proto.Chat.ChatMessageResult.getDefaultInstance()) return this;
        if (!other.getFrom().isEmpty()) {
          from_ = other.from_;
          onChanged();
        }
        if (other.getToAll() != false) {
          setToAll(other.getToAll());
        }
        if (!other.to_.isEmpty()) {
          if (to_.isEmpty()) {
            to_ = other.to_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureToIsMutable();
            to_.addAll(other.to_);
          }
          onChanged();
        }
        if (other.hasChatMessage()) {
          mergeChatMessage(other.getChatMessage());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.krossframework.proto.Chat.ChatMessageResult parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.krossframework.proto.Chat.ChatMessageResult) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object from_ = "";
      /**
       * <code>optional string from = 1;</code>
       */
      public java.lang.String getFrom() {
        java.lang.Object ref = from_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          from_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string from = 1;</code>
       */
      public com.google.protobuf.ByteString
          getFromBytes() {
        java.lang.Object ref = from_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          from_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string from = 1;</code>
       */
      public Builder setFrom(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        from_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string from = 1;</code>
       */
      public Builder clearFrom() {
        
        from_ = getDefaultInstance().getFrom();
        onChanged();
        return this;
      }
      /**
       * <code>optional string from = 1;</code>
       */
      public Builder setFromBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        from_ = value;
        onChanged();
        return this;
      }

      private boolean toAll_ ;
      /**
       * <code>optional bool toAll = 2;</code>
       */
      public boolean getToAll() {
        return toAll_;
      }
      /**
       * <code>optional bool toAll = 2;</code>
       */
      public Builder setToAll(boolean value) {
        
        toAll_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool toAll = 2;</code>
       */
      public Builder clearToAll() {
        
        toAll_ = false;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList to_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureToIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          to_ = new com.google.protobuf.LazyStringArrayList(to_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated string to = 3;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getToList() {
        return to_.getUnmodifiableView();
      }
      /**
       * <code>repeated string to = 3;</code>
       */
      public int getToCount() {
        return to_.size();
      }
      /**
       * <code>repeated string to = 3;</code>
       */
      public java.lang.String getTo(int index) {
        return to_.get(index);
      }
      /**
       * <code>repeated string to = 3;</code>
       */
      public com.google.protobuf.ByteString
          getToBytes(int index) {
        return to_.getByteString(index);
      }
      /**
       * <code>repeated string to = 3;</code>
       */
      public Builder setTo(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureToIsMutable();
        to_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string to = 3;</code>
       */
      public Builder addTo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureToIsMutable();
        to_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string to = 3;</code>
       */
      public Builder addAllTo(
          java.lang.Iterable<java.lang.String> values) {
        ensureToIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, to_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string to = 3;</code>
       */
      public Builder clearTo() {
        to_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string to = 3;</code>
       */
      public Builder addToBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureToIsMutable();
        to_.add(value);
        onChanged();
        return this;
      }

      private cn.krossframework.proto.Chat.ChatMessage chatMessage_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          cn.krossframework.proto.Chat.ChatMessage, cn.krossframework.proto.Chat.ChatMessage.Builder, cn.krossframework.proto.Chat.ChatMessageOrBuilder> chatMessageBuilder_;
      /**
       * <code>optional .cn.krossframework.proto.ChatMessage chatMessage = 4;</code>
       */
      public boolean hasChatMessage() {
        return chatMessageBuilder_ != null || chatMessage_ != null;
      }
      /**
       * <code>optional .cn.krossframework.proto.ChatMessage chatMessage = 4;</code>
       */
      public cn.krossframework.proto.Chat.ChatMessage getChatMessage() {
        if (chatMessageBuilder_ == null) {
          return chatMessage_ == null ? cn.krossframework.proto.Chat.ChatMessage.getDefaultInstance() : chatMessage_;
        } else {
          return chatMessageBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .cn.krossframework.proto.ChatMessage chatMessage = 4;</code>
       */
      public Builder setChatMessage(cn.krossframework.proto.Chat.ChatMessage value) {
        if (chatMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          chatMessage_ = value;
          onChanged();
        } else {
          chatMessageBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .cn.krossframework.proto.ChatMessage chatMessage = 4;</code>
       */
      public Builder setChatMessage(
          cn.krossframework.proto.Chat.ChatMessage.Builder builderForValue) {
        if (chatMessageBuilder_ == null) {
          chatMessage_ = builderForValue.build();
          onChanged();
        } else {
          chatMessageBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .cn.krossframework.proto.ChatMessage chatMessage = 4;</code>
       */
      public Builder mergeChatMessage(cn.krossframework.proto.Chat.ChatMessage value) {
        if (chatMessageBuilder_ == null) {
          if (chatMessage_ != null) {
            chatMessage_ =
              cn.krossframework.proto.Chat.ChatMessage.newBuilder(chatMessage_).mergeFrom(value).buildPartial();
          } else {
            chatMessage_ = value;
          }
          onChanged();
        } else {
          chatMessageBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .cn.krossframework.proto.ChatMessage chatMessage = 4;</code>
       */
      public Builder clearChatMessage() {
        if (chatMessageBuilder_ == null) {
          chatMessage_ = null;
          onChanged();
        } else {
          chatMessage_ = null;
          chatMessageBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .cn.krossframework.proto.ChatMessage chatMessage = 4;</code>
       */
      public cn.krossframework.proto.Chat.ChatMessage.Builder getChatMessageBuilder() {
        
        onChanged();
        return getChatMessageFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .cn.krossframework.proto.ChatMessage chatMessage = 4;</code>
       */
      public cn.krossframework.proto.Chat.ChatMessageOrBuilder getChatMessageOrBuilder() {
        if (chatMessageBuilder_ != null) {
          return chatMessageBuilder_.getMessageOrBuilder();
        } else {
          return chatMessage_ == null ?
              cn.krossframework.proto.Chat.ChatMessage.getDefaultInstance() : chatMessage_;
        }
      }
      /**
       * <code>optional .cn.krossframework.proto.ChatMessage chatMessage = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          cn.krossframework.proto.Chat.ChatMessage, cn.krossframework.proto.Chat.ChatMessage.Builder, cn.krossframework.proto.Chat.ChatMessageOrBuilder> 
          getChatMessageFieldBuilder() {
        if (chatMessageBuilder_ == null) {
          chatMessageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              cn.krossframework.proto.Chat.ChatMessage, cn.krossframework.proto.Chat.ChatMessage.Builder, cn.krossframework.proto.Chat.ChatMessageOrBuilder>(
                  getChatMessage(),
                  getParentForChildren(),
                  isClean());
          chatMessage_ = null;
        }
        return chatMessageBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:cn.krossframework.proto.ChatMessageResult)
    }

    // @@protoc_insertion_point(class_scope:cn.krossframework.proto.ChatMessageResult)
    private static final cn.krossframework.proto.Chat.ChatMessageResult DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.krossframework.proto.Chat.ChatMessageResult();
    }

    public static cn.krossframework.proto.Chat.ChatMessageResult getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ChatMessageResult>
        PARSER = new com.google.protobuf.AbstractParser<ChatMessageResult>() {
      public ChatMessageResult parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ChatMessageResult(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ChatMessageResult> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ChatMessageResult> getParserForType() {
      return PARSER;
    }

    public cn.krossframework.proto.Chat.ChatMessageResult getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_krossframework_proto_ChatMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_krossframework_proto_ChatMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_krossframework_proto_ChatMessageResult_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_krossframework_proto_ChatMessageResult_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nChat.proto\022\027cn.krossframework.proto\"M\n" +
      "\013ChatMessage\022\017\n\007cmdType\030\001 \001(\005\022\013\n\003msg\030\002 \001" +
      "(\t\022\020\n\010emoticon\030\003 \001(\005\022\016\n\006stream\030\004 \001(\014\"w\n\021" +
      "ChatMessageResult\022\014\n\004from\030\001 \001(\t\022\r\n\005toAll" +
      "\030\002 \001(\010\022\n\n\002to\030\003 \003(\t\0229\n\013chatMessage\030\004 \001(\0132" +
      "$.cn.krossframework.proto.ChatMessageB\010B" +
      "\004ChatH\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_cn_krossframework_proto_ChatMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cn_krossframework_proto_ChatMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_krossframework_proto_ChatMessage_descriptor,
        new java.lang.String[] { "CmdType", "Msg", "Emoticon", "Stream", });
    internal_static_cn_krossframework_proto_ChatMessageResult_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_cn_krossframework_proto_ChatMessageResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_krossframework_proto_ChatMessageResult_descriptor,
        new java.lang.String[] { "From", "ToAll", "To", "ChatMessage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
