// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Game.proto

package cn.krossframework.proto;

public final class Game {
  private Game() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PlayerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cn.krossframework.proto.Player)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string uid = 1;</code>
     */
    java.lang.String getUid();
    /**
     * <code>optional string uid = 1;</code>
     */
    com.google.protobuf.ByteString
        getUidBytes();

    /**
     * <code>optional string nickname = 2;</code>
     */
    java.lang.String getNickname();
    /**
     * <code>optional string nickname = 2;</code>
     */
    com.google.protobuf.ByteString
        getNicknameBytes();

    /**
     * <code>optional string headIcon = 3;</code>
     */
    java.lang.String getHeadIcon();
    /**
     * <code>optional string headIcon = 3;</code>
     */
    com.google.protobuf.ByteString
        getHeadIconBytes();
  }
  /**
   * Protobuf type {@code cn.krossframework.proto.Player}
   */
  public  static final class Player extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cn.krossframework.proto.Player)
      PlayerOrBuilder {
    // Use Player.newBuilder() to construct.
    private Player(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Player() {
      uid_ = "";
      nickname_ = "";
      headIcon_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Player(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              uid_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              nickname_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              headIcon_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.krossframework.proto.Game.internal_static_cn_krossframework_proto_Player_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.krossframework.proto.Game.internal_static_cn_krossframework_proto_Player_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.krossframework.proto.Game.Player.class, cn.krossframework.proto.Game.Player.Builder.class);
    }

    public static final int UID_FIELD_NUMBER = 1;
    private volatile java.lang.Object uid_;
    /**
     * <code>optional string uid = 1;</code>
     */
    public java.lang.String getUid() {
      java.lang.Object ref = uid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uid_ = s;
        return s;
      }
    }
    /**
     * <code>optional string uid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUidBytes() {
      java.lang.Object ref = uid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NICKNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object nickname_;
    /**
     * <code>optional string nickname = 2;</code>
     */
    public java.lang.String getNickname() {
      java.lang.Object ref = nickname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nickname_ = s;
        return s;
      }
    }
    /**
     * <code>optional string nickname = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNicknameBytes() {
      java.lang.Object ref = nickname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nickname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HEADICON_FIELD_NUMBER = 3;
    private volatile java.lang.Object headIcon_;
    /**
     * <code>optional string headIcon = 3;</code>
     */
    public java.lang.String getHeadIcon() {
      java.lang.Object ref = headIcon_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        headIcon_ = s;
        return s;
      }
    }
    /**
     * <code>optional string headIcon = 3;</code>
     */
    public com.google.protobuf.ByteString
        getHeadIconBytes() {
      java.lang.Object ref = headIcon_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        headIcon_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getUidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, uid_);
      }
      if (!getNicknameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, nickname_);
      }
      if (!getHeadIconBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, headIcon_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getUidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, uid_);
      }
      if (!getNicknameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, nickname_);
      }
      if (!getHeadIconBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, headIcon_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.krossframework.proto.Game.Player)) {
        return super.equals(obj);
      }
      cn.krossframework.proto.Game.Player other = (cn.krossframework.proto.Game.Player) obj;

      boolean result = true;
      result = result && getUid()
          .equals(other.getUid());
      result = result && getNickname()
          .equals(other.getNickname());
      result = result && getHeadIcon()
          .equals(other.getHeadIcon());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + UID_FIELD_NUMBER;
      hash = (53 * hash) + getUid().hashCode();
      hash = (37 * hash) + NICKNAME_FIELD_NUMBER;
      hash = (53 * hash) + getNickname().hashCode();
      hash = (37 * hash) + HEADICON_FIELD_NUMBER;
      hash = (53 * hash) + getHeadIcon().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.krossframework.proto.Game.Player parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.krossframework.proto.Game.Player parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.krossframework.proto.Game.Player parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.krossframework.proto.Game.Player parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.krossframework.proto.Game.Player parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.krossframework.proto.Game.Player parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.krossframework.proto.Game.Player parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.krossframework.proto.Game.Player parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.krossframework.proto.Game.Player parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.krossframework.proto.Game.Player parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.krossframework.proto.Game.Player prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cn.krossframework.proto.Player}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cn.krossframework.proto.Player)
        cn.krossframework.proto.Game.PlayerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.krossframework.proto.Game.internal_static_cn_krossframework_proto_Player_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.krossframework.proto.Game.internal_static_cn_krossframework_proto_Player_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.krossframework.proto.Game.Player.class, cn.krossframework.proto.Game.Player.Builder.class);
      }

      // Construct using cn.krossframework.proto.Game.Player.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        uid_ = "";

        nickname_ = "";

        headIcon_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.krossframework.proto.Game.internal_static_cn_krossframework_proto_Player_descriptor;
      }

      public cn.krossframework.proto.Game.Player getDefaultInstanceForType() {
        return cn.krossframework.proto.Game.Player.getDefaultInstance();
      }

      public cn.krossframework.proto.Game.Player build() {
        cn.krossframework.proto.Game.Player result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cn.krossframework.proto.Game.Player buildPartial() {
        cn.krossframework.proto.Game.Player result = new cn.krossframework.proto.Game.Player(this);
        result.uid_ = uid_;
        result.nickname_ = nickname_;
        result.headIcon_ = headIcon_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.krossframework.proto.Game.Player) {
          return mergeFrom((cn.krossframework.proto.Game.Player)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.krossframework.proto.Game.Player other) {
        if (other == cn.krossframework.proto.Game.Player.getDefaultInstance()) return this;
        if (!other.getUid().isEmpty()) {
          uid_ = other.uid_;
          onChanged();
        }
        if (!other.getNickname().isEmpty()) {
          nickname_ = other.nickname_;
          onChanged();
        }
        if (!other.getHeadIcon().isEmpty()) {
          headIcon_ = other.headIcon_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.krossframework.proto.Game.Player parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.krossframework.proto.Game.Player) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object uid_ = "";
      /**
       * <code>optional string uid = 1;</code>
       */
      public java.lang.String getUid() {
        java.lang.Object ref = uid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          uid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string uid = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUidBytes() {
        java.lang.Object ref = uid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string uid = 1;</code>
       */
      public Builder setUid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string uid = 1;</code>
       */
      public Builder clearUid() {
        
        uid_ = getDefaultInstance().getUid();
        onChanged();
        return this;
      }
      /**
       * <code>optional string uid = 1;</code>
       */
      public Builder setUidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        uid_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object nickname_ = "";
      /**
       * <code>optional string nickname = 2;</code>
       */
      public java.lang.String getNickname() {
        java.lang.Object ref = nickname_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nickname_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string nickname = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNicknameBytes() {
        java.lang.Object ref = nickname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nickname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string nickname = 2;</code>
       */
      public Builder setNickname(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nickname_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string nickname = 2;</code>
       */
      public Builder clearNickname() {
        
        nickname_ = getDefaultInstance().getNickname();
        onChanged();
        return this;
      }
      /**
       * <code>optional string nickname = 2;</code>
       */
      public Builder setNicknameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        nickname_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object headIcon_ = "";
      /**
       * <code>optional string headIcon = 3;</code>
       */
      public java.lang.String getHeadIcon() {
        java.lang.Object ref = headIcon_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          headIcon_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string headIcon = 3;</code>
       */
      public com.google.protobuf.ByteString
          getHeadIconBytes() {
        java.lang.Object ref = headIcon_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          headIcon_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string headIcon = 3;</code>
       */
      public Builder setHeadIcon(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        headIcon_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string headIcon = 3;</code>
       */
      public Builder clearHeadIcon() {
        
        headIcon_ = getDefaultInstance().getHeadIcon();
        onChanged();
        return this;
      }
      /**
       * <code>optional string headIcon = 3;</code>
       */
      public Builder setHeadIconBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        headIcon_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:cn.krossframework.proto.Player)
    }

    // @@protoc_insertion_point(class_scope:cn.krossframework.proto.Player)
    private static final cn.krossframework.proto.Game.Player DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.krossframework.proto.Game.Player();
    }

    public static cn.krossframework.proto.Game.Player getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Player>
        PARSER = new com.google.protobuf.AbstractParser<Player>() {
      public Player parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Player(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Player> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Player> getParserForType() {
      return PARSER;
    }

    public cn.krossframework.proto.Game.Player getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TetrisSeatDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cn.krossframework.proto.TetrisSeatData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 score = 1;</code>
     */
    int getScore();

    /**
     * <code>optional .cn.krossframework.proto.Player player = 2;</code>
     */
    boolean hasPlayer();
    /**
     * <code>optional .cn.krossframework.proto.Player player = 2;</code>
     */
    cn.krossframework.proto.Game.Player getPlayer();
    /**
     * <code>optional .cn.krossframework.proto.Player player = 2;</code>
     */
    cn.krossframework.proto.Game.PlayerOrBuilder getPlayerOrBuilder();
  }
  /**
   * Protobuf type {@code cn.krossframework.proto.TetrisSeatData}
   */
  public  static final class TetrisSeatData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cn.krossframework.proto.TetrisSeatData)
      TetrisSeatDataOrBuilder {
    // Use TetrisSeatData.newBuilder() to construct.
    private TetrisSeatData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TetrisSeatData() {
      score_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private TetrisSeatData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              score_ = input.readInt32();
              break;
            }
            case 18: {
              cn.krossframework.proto.Game.Player.Builder subBuilder = null;
              if (player_ != null) {
                subBuilder = player_.toBuilder();
              }
              player_ = input.readMessage(cn.krossframework.proto.Game.Player.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(player_);
                player_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.krossframework.proto.Game.internal_static_cn_krossframework_proto_TetrisSeatData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.krossframework.proto.Game.internal_static_cn_krossframework_proto_TetrisSeatData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.krossframework.proto.Game.TetrisSeatData.class, cn.krossframework.proto.Game.TetrisSeatData.Builder.class);
    }

    public static final int SCORE_FIELD_NUMBER = 1;
    private int score_;
    /**
     * <code>optional int32 score = 1;</code>
     */
    public int getScore() {
      return score_;
    }

    public static final int PLAYER_FIELD_NUMBER = 2;
    private cn.krossframework.proto.Game.Player player_;
    /**
     * <code>optional .cn.krossframework.proto.Player player = 2;</code>
     */
    public boolean hasPlayer() {
      return player_ != null;
    }
    /**
     * <code>optional .cn.krossframework.proto.Player player = 2;</code>
     */
    public cn.krossframework.proto.Game.Player getPlayer() {
      return player_ == null ? cn.krossframework.proto.Game.Player.getDefaultInstance() : player_;
    }
    /**
     * <code>optional .cn.krossframework.proto.Player player = 2;</code>
     */
    public cn.krossframework.proto.Game.PlayerOrBuilder getPlayerOrBuilder() {
      return getPlayer();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (score_ != 0) {
        output.writeInt32(1, score_);
      }
      if (player_ != null) {
        output.writeMessage(2, getPlayer());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (score_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, score_);
      }
      if (player_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getPlayer());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.krossframework.proto.Game.TetrisSeatData)) {
        return super.equals(obj);
      }
      cn.krossframework.proto.Game.TetrisSeatData other = (cn.krossframework.proto.Game.TetrisSeatData) obj;

      boolean result = true;
      result = result && (getScore()
          == other.getScore());
      result = result && (hasPlayer() == other.hasPlayer());
      if (hasPlayer()) {
        result = result && getPlayer()
            .equals(other.getPlayer());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + SCORE_FIELD_NUMBER;
      hash = (53 * hash) + getScore();
      if (hasPlayer()) {
        hash = (37 * hash) + PLAYER_FIELD_NUMBER;
        hash = (53 * hash) + getPlayer().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.krossframework.proto.Game.TetrisSeatData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.krossframework.proto.Game.TetrisSeatData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.krossframework.proto.Game.TetrisSeatData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.krossframework.proto.Game.TetrisSeatData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.krossframework.proto.Game.TetrisSeatData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.krossframework.proto.Game.TetrisSeatData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.krossframework.proto.Game.TetrisSeatData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.krossframework.proto.Game.TetrisSeatData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.krossframework.proto.Game.TetrisSeatData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.krossframework.proto.Game.TetrisSeatData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.krossframework.proto.Game.TetrisSeatData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cn.krossframework.proto.TetrisSeatData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cn.krossframework.proto.TetrisSeatData)
        cn.krossframework.proto.Game.TetrisSeatDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.krossframework.proto.Game.internal_static_cn_krossframework_proto_TetrisSeatData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.krossframework.proto.Game.internal_static_cn_krossframework_proto_TetrisSeatData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.krossframework.proto.Game.TetrisSeatData.class, cn.krossframework.proto.Game.TetrisSeatData.Builder.class);
      }

      // Construct using cn.krossframework.proto.Game.TetrisSeatData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        score_ = 0;

        if (playerBuilder_ == null) {
          player_ = null;
        } else {
          player_ = null;
          playerBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.krossframework.proto.Game.internal_static_cn_krossframework_proto_TetrisSeatData_descriptor;
      }

      public cn.krossframework.proto.Game.TetrisSeatData getDefaultInstanceForType() {
        return cn.krossframework.proto.Game.TetrisSeatData.getDefaultInstance();
      }

      public cn.krossframework.proto.Game.TetrisSeatData build() {
        cn.krossframework.proto.Game.TetrisSeatData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cn.krossframework.proto.Game.TetrisSeatData buildPartial() {
        cn.krossframework.proto.Game.TetrisSeatData result = new cn.krossframework.proto.Game.TetrisSeatData(this);
        result.score_ = score_;
        if (playerBuilder_ == null) {
          result.player_ = player_;
        } else {
          result.player_ = playerBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.krossframework.proto.Game.TetrisSeatData) {
          return mergeFrom((cn.krossframework.proto.Game.TetrisSeatData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.krossframework.proto.Game.TetrisSeatData other) {
        if (other == cn.krossframework.proto.Game.TetrisSeatData.getDefaultInstance()) return this;
        if (other.getScore() != 0) {
          setScore(other.getScore());
        }
        if (other.hasPlayer()) {
          mergePlayer(other.getPlayer());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.krossframework.proto.Game.TetrisSeatData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.krossframework.proto.Game.TetrisSeatData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int score_ ;
      /**
       * <code>optional int32 score = 1;</code>
       */
      public int getScore() {
        return score_;
      }
      /**
       * <code>optional int32 score = 1;</code>
       */
      public Builder setScore(int value) {
        
        score_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 score = 1;</code>
       */
      public Builder clearScore() {
        
        score_ = 0;
        onChanged();
        return this;
      }

      private cn.krossframework.proto.Game.Player player_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          cn.krossframework.proto.Game.Player, cn.krossframework.proto.Game.Player.Builder, cn.krossframework.proto.Game.PlayerOrBuilder> playerBuilder_;
      /**
       * <code>optional .cn.krossframework.proto.Player player = 2;</code>
       */
      public boolean hasPlayer() {
        return playerBuilder_ != null || player_ != null;
      }
      /**
       * <code>optional .cn.krossframework.proto.Player player = 2;</code>
       */
      public cn.krossframework.proto.Game.Player getPlayer() {
        if (playerBuilder_ == null) {
          return player_ == null ? cn.krossframework.proto.Game.Player.getDefaultInstance() : player_;
        } else {
          return playerBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .cn.krossframework.proto.Player player = 2;</code>
       */
      public Builder setPlayer(cn.krossframework.proto.Game.Player value) {
        if (playerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          player_ = value;
          onChanged();
        } else {
          playerBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .cn.krossframework.proto.Player player = 2;</code>
       */
      public Builder setPlayer(
          cn.krossframework.proto.Game.Player.Builder builderForValue) {
        if (playerBuilder_ == null) {
          player_ = builderForValue.build();
          onChanged();
        } else {
          playerBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .cn.krossframework.proto.Player player = 2;</code>
       */
      public Builder mergePlayer(cn.krossframework.proto.Game.Player value) {
        if (playerBuilder_ == null) {
          if (player_ != null) {
            player_ =
              cn.krossframework.proto.Game.Player.newBuilder(player_).mergeFrom(value).buildPartial();
          } else {
            player_ = value;
          }
          onChanged();
        } else {
          playerBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .cn.krossframework.proto.Player player = 2;</code>
       */
      public Builder clearPlayer() {
        if (playerBuilder_ == null) {
          player_ = null;
          onChanged();
        } else {
          player_ = null;
          playerBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .cn.krossframework.proto.Player player = 2;</code>
       */
      public cn.krossframework.proto.Game.Player.Builder getPlayerBuilder() {
        
        onChanged();
        return getPlayerFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .cn.krossframework.proto.Player player = 2;</code>
       */
      public cn.krossframework.proto.Game.PlayerOrBuilder getPlayerOrBuilder() {
        if (playerBuilder_ != null) {
          return playerBuilder_.getMessageOrBuilder();
        } else {
          return player_ == null ?
              cn.krossframework.proto.Game.Player.getDefaultInstance() : player_;
        }
      }
      /**
       * <code>optional .cn.krossframework.proto.Player player = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          cn.krossframework.proto.Game.Player, cn.krossframework.proto.Game.Player.Builder, cn.krossframework.proto.Game.PlayerOrBuilder> 
          getPlayerFieldBuilder() {
        if (playerBuilder_ == null) {
          playerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              cn.krossframework.proto.Game.Player, cn.krossframework.proto.Game.Player.Builder, cn.krossframework.proto.Game.PlayerOrBuilder>(
                  getPlayer(),
                  getParentForChildren(),
                  isClean());
          player_ = null;
        }
        return playerBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:cn.krossframework.proto.TetrisSeatData)
    }

    // @@protoc_insertion_point(class_scope:cn.krossframework.proto.TetrisSeatData)
    private static final cn.krossframework.proto.Game.TetrisSeatData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.krossframework.proto.Game.TetrisSeatData();
    }

    public static cn.krossframework.proto.Game.TetrisSeatData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TetrisSeatData>
        PARSER = new com.google.protobuf.AbstractParser<TetrisSeatData>() {
      public TetrisSeatData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new TetrisSeatData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TetrisSeatData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TetrisSeatData> getParserForType() {
      return PARSER;
    }

    public cn.krossframework.proto.Game.TetrisSeatData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TetrisRoomDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cn.krossframework.proto.TetrisRoomData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .cn.krossframework.proto.TetrisSeatData tetrisSeatDataList = 1;</code>
     */
    java.util.List<cn.krossframework.proto.Game.TetrisSeatData> 
        getTetrisSeatDataListList();
    /**
     * <code>repeated .cn.krossframework.proto.TetrisSeatData tetrisSeatDataList = 1;</code>
     */
    cn.krossframework.proto.Game.TetrisSeatData getTetrisSeatDataList(int index);
    /**
     * <code>repeated .cn.krossframework.proto.TetrisSeatData tetrisSeatDataList = 1;</code>
     */
    int getTetrisSeatDataListCount();
    /**
     * <code>repeated .cn.krossframework.proto.TetrisSeatData tetrisSeatDataList = 1;</code>
     */
    java.util.List<? extends cn.krossframework.proto.Game.TetrisSeatDataOrBuilder> 
        getTetrisSeatDataListOrBuilderList();
    /**
     * <code>repeated .cn.krossframework.proto.TetrisSeatData tetrisSeatDataList = 1;</code>
     */
    cn.krossframework.proto.Game.TetrisSeatDataOrBuilder getTetrisSeatDataListOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code cn.krossframework.proto.TetrisRoomData}
   */
  public  static final class TetrisRoomData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cn.krossframework.proto.TetrisRoomData)
      TetrisRoomDataOrBuilder {
    // Use TetrisRoomData.newBuilder() to construct.
    private TetrisRoomData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TetrisRoomData() {
      tetrisSeatDataList_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private TetrisRoomData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                tetrisSeatDataList_ = new java.util.ArrayList<cn.krossframework.proto.Game.TetrisSeatData>();
                mutable_bitField0_ |= 0x00000001;
              }
              tetrisSeatDataList_.add(
                  input.readMessage(cn.krossframework.proto.Game.TetrisSeatData.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          tetrisSeatDataList_ = java.util.Collections.unmodifiableList(tetrisSeatDataList_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.krossframework.proto.Game.internal_static_cn_krossframework_proto_TetrisRoomData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.krossframework.proto.Game.internal_static_cn_krossframework_proto_TetrisRoomData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.krossframework.proto.Game.TetrisRoomData.class, cn.krossframework.proto.Game.TetrisRoomData.Builder.class);
    }

    public static final int TETRISSEATDATALIST_FIELD_NUMBER = 1;
    private java.util.List<cn.krossframework.proto.Game.TetrisSeatData> tetrisSeatDataList_;
    /**
     * <code>repeated .cn.krossframework.proto.TetrisSeatData tetrisSeatDataList = 1;</code>
     */
    public java.util.List<cn.krossframework.proto.Game.TetrisSeatData> getTetrisSeatDataListList() {
      return tetrisSeatDataList_;
    }
    /**
     * <code>repeated .cn.krossframework.proto.TetrisSeatData tetrisSeatDataList = 1;</code>
     */
    public java.util.List<? extends cn.krossframework.proto.Game.TetrisSeatDataOrBuilder> 
        getTetrisSeatDataListOrBuilderList() {
      return tetrisSeatDataList_;
    }
    /**
     * <code>repeated .cn.krossframework.proto.TetrisSeatData tetrisSeatDataList = 1;</code>
     */
    public int getTetrisSeatDataListCount() {
      return tetrisSeatDataList_.size();
    }
    /**
     * <code>repeated .cn.krossframework.proto.TetrisSeatData tetrisSeatDataList = 1;</code>
     */
    public cn.krossframework.proto.Game.TetrisSeatData getTetrisSeatDataList(int index) {
      return tetrisSeatDataList_.get(index);
    }
    /**
     * <code>repeated .cn.krossframework.proto.TetrisSeatData tetrisSeatDataList = 1;</code>
     */
    public cn.krossframework.proto.Game.TetrisSeatDataOrBuilder getTetrisSeatDataListOrBuilder(
        int index) {
      return tetrisSeatDataList_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < tetrisSeatDataList_.size(); i++) {
        output.writeMessage(1, tetrisSeatDataList_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < tetrisSeatDataList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, tetrisSeatDataList_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.krossframework.proto.Game.TetrisRoomData)) {
        return super.equals(obj);
      }
      cn.krossframework.proto.Game.TetrisRoomData other = (cn.krossframework.proto.Game.TetrisRoomData) obj;

      boolean result = true;
      result = result && getTetrisSeatDataListList()
          .equals(other.getTetrisSeatDataListList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getTetrisSeatDataListCount() > 0) {
        hash = (37 * hash) + TETRISSEATDATALIST_FIELD_NUMBER;
        hash = (53 * hash) + getTetrisSeatDataListList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.krossframework.proto.Game.TetrisRoomData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.krossframework.proto.Game.TetrisRoomData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.krossframework.proto.Game.TetrisRoomData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.krossframework.proto.Game.TetrisRoomData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.krossframework.proto.Game.TetrisRoomData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.krossframework.proto.Game.TetrisRoomData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.krossframework.proto.Game.TetrisRoomData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.krossframework.proto.Game.TetrisRoomData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.krossframework.proto.Game.TetrisRoomData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.krossframework.proto.Game.TetrisRoomData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.krossframework.proto.Game.TetrisRoomData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cn.krossframework.proto.TetrisRoomData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cn.krossframework.proto.TetrisRoomData)
        cn.krossframework.proto.Game.TetrisRoomDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.krossframework.proto.Game.internal_static_cn_krossframework_proto_TetrisRoomData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.krossframework.proto.Game.internal_static_cn_krossframework_proto_TetrisRoomData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.krossframework.proto.Game.TetrisRoomData.class, cn.krossframework.proto.Game.TetrisRoomData.Builder.class);
      }

      // Construct using cn.krossframework.proto.Game.TetrisRoomData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getTetrisSeatDataListFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (tetrisSeatDataListBuilder_ == null) {
          tetrisSeatDataList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          tetrisSeatDataListBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.krossframework.proto.Game.internal_static_cn_krossframework_proto_TetrisRoomData_descriptor;
      }

      public cn.krossframework.proto.Game.TetrisRoomData getDefaultInstanceForType() {
        return cn.krossframework.proto.Game.TetrisRoomData.getDefaultInstance();
      }

      public cn.krossframework.proto.Game.TetrisRoomData build() {
        cn.krossframework.proto.Game.TetrisRoomData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cn.krossframework.proto.Game.TetrisRoomData buildPartial() {
        cn.krossframework.proto.Game.TetrisRoomData result = new cn.krossframework.proto.Game.TetrisRoomData(this);
        int from_bitField0_ = bitField0_;
        if (tetrisSeatDataListBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            tetrisSeatDataList_ = java.util.Collections.unmodifiableList(tetrisSeatDataList_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.tetrisSeatDataList_ = tetrisSeatDataList_;
        } else {
          result.tetrisSeatDataList_ = tetrisSeatDataListBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.krossframework.proto.Game.TetrisRoomData) {
          return mergeFrom((cn.krossframework.proto.Game.TetrisRoomData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.krossframework.proto.Game.TetrisRoomData other) {
        if (other == cn.krossframework.proto.Game.TetrisRoomData.getDefaultInstance()) return this;
        if (tetrisSeatDataListBuilder_ == null) {
          if (!other.tetrisSeatDataList_.isEmpty()) {
            if (tetrisSeatDataList_.isEmpty()) {
              tetrisSeatDataList_ = other.tetrisSeatDataList_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureTetrisSeatDataListIsMutable();
              tetrisSeatDataList_.addAll(other.tetrisSeatDataList_);
            }
            onChanged();
          }
        } else {
          if (!other.tetrisSeatDataList_.isEmpty()) {
            if (tetrisSeatDataListBuilder_.isEmpty()) {
              tetrisSeatDataListBuilder_.dispose();
              tetrisSeatDataListBuilder_ = null;
              tetrisSeatDataList_ = other.tetrisSeatDataList_;
              bitField0_ = (bitField0_ & ~0x00000001);
              tetrisSeatDataListBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getTetrisSeatDataListFieldBuilder() : null;
            } else {
              tetrisSeatDataListBuilder_.addAllMessages(other.tetrisSeatDataList_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.krossframework.proto.Game.TetrisRoomData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.krossframework.proto.Game.TetrisRoomData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<cn.krossframework.proto.Game.TetrisSeatData> tetrisSeatDataList_ =
        java.util.Collections.emptyList();
      private void ensureTetrisSeatDataListIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          tetrisSeatDataList_ = new java.util.ArrayList<cn.krossframework.proto.Game.TetrisSeatData>(tetrisSeatDataList_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          cn.krossframework.proto.Game.TetrisSeatData, cn.krossframework.proto.Game.TetrisSeatData.Builder, cn.krossframework.proto.Game.TetrisSeatDataOrBuilder> tetrisSeatDataListBuilder_;

      /**
       * <code>repeated .cn.krossframework.proto.TetrisSeatData tetrisSeatDataList = 1;</code>
       */
      public java.util.List<cn.krossframework.proto.Game.TetrisSeatData> getTetrisSeatDataListList() {
        if (tetrisSeatDataListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(tetrisSeatDataList_);
        } else {
          return tetrisSeatDataListBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .cn.krossframework.proto.TetrisSeatData tetrisSeatDataList = 1;</code>
       */
      public int getTetrisSeatDataListCount() {
        if (tetrisSeatDataListBuilder_ == null) {
          return tetrisSeatDataList_.size();
        } else {
          return tetrisSeatDataListBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .cn.krossframework.proto.TetrisSeatData tetrisSeatDataList = 1;</code>
       */
      public cn.krossframework.proto.Game.TetrisSeatData getTetrisSeatDataList(int index) {
        if (tetrisSeatDataListBuilder_ == null) {
          return tetrisSeatDataList_.get(index);
        } else {
          return tetrisSeatDataListBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .cn.krossframework.proto.TetrisSeatData tetrisSeatDataList = 1;</code>
       */
      public Builder setTetrisSeatDataList(
          int index, cn.krossframework.proto.Game.TetrisSeatData value) {
        if (tetrisSeatDataListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTetrisSeatDataListIsMutable();
          tetrisSeatDataList_.set(index, value);
          onChanged();
        } else {
          tetrisSeatDataListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .cn.krossframework.proto.TetrisSeatData tetrisSeatDataList = 1;</code>
       */
      public Builder setTetrisSeatDataList(
          int index, cn.krossframework.proto.Game.TetrisSeatData.Builder builderForValue) {
        if (tetrisSeatDataListBuilder_ == null) {
          ensureTetrisSeatDataListIsMutable();
          tetrisSeatDataList_.set(index, builderForValue.build());
          onChanged();
        } else {
          tetrisSeatDataListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .cn.krossframework.proto.TetrisSeatData tetrisSeatDataList = 1;</code>
       */
      public Builder addTetrisSeatDataList(cn.krossframework.proto.Game.TetrisSeatData value) {
        if (tetrisSeatDataListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTetrisSeatDataListIsMutable();
          tetrisSeatDataList_.add(value);
          onChanged();
        } else {
          tetrisSeatDataListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .cn.krossframework.proto.TetrisSeatData tetrisSeatDataList = 1;</code>
       */
      public Builder addTetrisSeatDataList(
          int index, cn.krossframework.proto.Game.TetrisSeatData value) {
        if (tetrisSeatDataListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTetrisSeatDataListIsMutable();
          tetrisSeatDataList_.add(index, value);
          onChanged();
        } else {
          tetrisSeatDataListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .cn.krossframework.proto.TetrisSeatData tetrisSeatDataList = 1;</code>
       */
      public Builder addTetrisSeatDataList(
          cn.krossframework.proto.Game.TetrisSeatData.Builder builderForValue) {
        if (tetrisSeatDataListBuilder_ == null) {
          ensureTetrisSeatDataListIsMutable();
          tetrisSeatDataList_.add(builderForValue.build());
          onChanged();
        } else {
          tetrisSeatDataListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .cn.krossframework.proto.TetrisSeatData tetrisSeatDataList = 1;</code>
       */
      public Builder addTetrisSeatDataList(
          int index, cn.krossframework.proto.Game.TetrisSeatData.Builder builderForValue) {
        if (tetrisSeatDataListBuilder_ == null) {
          ensureTetrisSeatDataListIsMutable();
          tetrisSeatDataList_.add(index, builderForValue.build());
          onChanged();
        } else {
          tetrisSeatDataListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .cn.krossframework.proto.TetrisSeatData tetrisSeatDataList = 1;</code>
       */
      public Builder addAllTetrisSeatDataList(
          java.lang.Iterable<? extends cn.krossframework.proto.Game.TetrisSeatData> values) {
        if (tetrisSeatDataListBuilder_ == null) {
          ensureTetrisSeatDataListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, tetrisSeatDataList_);
          onChanged();
        } else {
          tetrisSeatDataListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .cn.krossframework.proto.TetrisSeatData tetrisSeatDataList = 1;</code>
       */
      public Builder clearTetrisSeatDataList() {
        if (tetrisSeatDataListBuilder_ == null) {
          tetrisSeatDataList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          tetrisSeatDataListBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .cn.krossframework.proto.TetrisSeatData tetrisSeatDataList = 1;</code>
       */
      public Builder removeTetrisSeatDataList(int index) {
        if (tetrisSeatDataListBuilder_ == null) {
          ensureTetrisSeatDataListIsMutable();
          tetrisSeatDataList_.remove(index);
          onChanged();
        } else {
          tetrisSeatDataListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .cn.krossframework.proto.TetrisSeatData tetrisSeatDataList = 1;</code>
       */
      public cn.krossframework.proto.Game.TetrisSeatData.Builder getTetrisSeatDataListBuilder(
          int index) {
        return getTetrisSeatDataListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .cn.krossframework.proto.TetrisSeatData tetrisSeatDataList = 1;</code>
       */
      public cn.krossframework.proto.Game.TetrisSeatDataOrBuilder getTetrisSeatDataListOrBuilder(
          int index) {
        if (tetrisSeatDataListBuilder_ == null) {
          return tetrisSeatDataList_.get(index);  } else {
          return tetrisSeatDataListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .cn.krossframework.proto.TetrisSeatData tetrisSeatDataList = 1;</code>
       */
      public java.util.List<? extends cn.krossframework.proto.Game.TetrisSeatDataOrBuilder> 
           getTetrisSeatDataListOrBuilderList() {
        if (tetrisSeatDataListBuilder_ != null) {
          return tetrisSeatDataListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(tetrisSeatDataList_);
        }
      }
      /**
       * <code>repeated .cn.krossframework.proto.TetrisSeatData tetrisSeatDataList = 1;</code>
       */
      public cn.krossframework.proto.Game.TetrisSeatData.Builder addTetrisSeatDataListBuilder() {
        return getTetrisSeatDataListFieldBuilder().addBuilder(
            cn.krossframework.proto.Game.TetrisSeatData.getDefaultInstance());
      }
      /**
       * <code>repeated .cn.krossframework.proto.TetrisSeatData tetrisSeatDataList = 1;</code>
       */
      public cn.krossframework.proto.Game.TetrisSeatData.Builder addTetrisSeatDataListBuilder(
          int index) {
        return getTetrisSeatDataListFieldBuilder().addBuilder(
            index, cn.krossframework.proto.Game.TetrisSeatData.getDefaultInstance());
      }
      /**
       * <code>repeated .cn.krossframework.proto.TetrisSeatData tetrisSeatDataList = 1;</code>
       */
      public java.util.List<cn.krossframework.proto.Game.TetrisSeatData.Builder> 
           getTetrisSeatDataListBuilderList() {
        return getTetrisSeatDataListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          cn.krossframework.proto.Game.TetrisSeatData, cn.krossframework.proto.Game.TetrisSeatData.Builder, cn.krossframework.proto.Game.TetrisSeatDataOrBuilder> 
          getTetrisSeatDataListFieldBuilder() {
        if (tetrisSeatDataListBuilder_ == null) {
          tetrisSeatDataListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              cn.krossframework.proto.Game.TetrisSeatData, cn.krossframework.proto.Game.TetrisSeatData.Builder, cn.krossframework.proto.Game.TetrisSeatDataOrBuilder>(
                  tetrisSeatDataList_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          tetrisSeatDataList_ = null;
        }
        return tetrisSeatDataListBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:cn.krossframework.proto.TetrisRoomData)
    }

    // @@protoc_insertion_point(class_scope:cn.krossframework.proto.TetrisRoomData)
    private static final cn.krossframework.proto.Game.TetrisRoomData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.krossframework.proto.Game.TetrisRoomData();
    }

    public static cn.krossframework.proto.Game.TetrisRoomData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TetrisRoomData>
        PARSER = new com.google.protobuf.AbstractParser<TetrisRoomData>() {
      public TetrisRoomData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new TetrisRoomData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TetrisRoomData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TetrisRoomData> getParserForType() {
      return PARSER;
    }

    public cn.krossframework.proto.Game.TetrisRoomData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_krossframework_proto_Player_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_krossframework_proto_Player_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_krossframework_proto_TetrisSeatData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_krossframework_proto_TetrisSeatData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_krossframework_proto_TetrisRoomData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_krossframework_proto_TetrisRoomData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nGame.proto\022\027cn.krossframework.proto\"9\n" +
      "\006Player\022\013\n\003uid\030\001 \001(\t\022\020\n\010nickname\030\002 \001(\t\022\020" +
      "\n\010headIcon\030\003 \001(\t\"P\n\016TetrisSeatData\022\r\n\005sc" +
      "ore\030\001 \001(\005\022/\n\006player\030\002 \001(\0132\037.cn.krossfram" +
      "ework.proto.Player\"U\n\016TetrisRoomData\022C\n\022" +
      "tetrisSeatDataList\030\001 \003(\0132\'.cn.krossframe" +
      "work.proto.TetrisSeatDataB\010B\004GameH\001b\006pro" +
      "to3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_cn_krossframework_proto_Player_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cn_krossframework_proto_Player_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_krossframework_proto_Player_descriptor,
        new java.lang.String[] { "Uid", "Nickname", "HeadIcon", });
    internal_static_cn_krossframework_proto_TetrisSeatData_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_cn_krossframework_proto_TetrisSeatData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_krossframework_proto_TetrisSeatData_descriptor,
        new java.lang.String[] { "Score", "Player", });
    internal_static_cn_krossframework_proto_TetrisRoomData_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_cn_krossframework_proto_TetrisRoomData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_krossframework_proto_TetrisRoomData_descriptor,
        new java.lang.String[] { "TetrisSeatDataList", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
