spring:
  netty:
    port: 8000
    protocolClass: cn.krossframework.websocket.ProtoWebSocketHandler
  state:
    workerUpdatePeriod: 20
    workerCapacity: 20
    workerThreadSize: 20
    removeEmptyWorkerPeriod: 0
    removeDeposedStateGroupPeriod: 0
    taskDispatcherSize: 10
